title: Mixed Reality Toolkit
description: MRTK3 is the third generation of the Mixed Reality Toolkit for Unity.
theme: just-the-docs
color_scheme: dark

url: https://mixedrealitytoolkit.github.io/MixedRealityToolkit-Unity/
logo: "/images/MRTK_Logo_White.png"
favicon_ico: "/images/IconMRTKLogo.png"

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

callouts_level: loud
callouts:
  note:
    title: ‚ÑπÔ∏è Note
    color: blue
  tip:
    title: üí° Tip
    color: green
  important:
    title: ‚ùïImportant
    color: purple
  warning:
    title: ‚ö†Ô∏è Warning
    color: yellow
  caution:
    title: üõë Caution
    color: red
