name: Code Validation

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Get Pull Request changes
      if: github.event_name == 'pull_request'
      run: |
        ${{ github.workspace }}/Pipelines/Scripts/gitchanges.ps1 -TargetBranch '${{ github.base_ref }}' -OutputFile '${{ runner.temp }}/build/changed_files.txt' -RepoRoot '${{ github.workspace }}'
      shell: pwsh

    - name: Scoped code validation
      if: github.event_name == 'pull_request'
      run: |
        ${{ github.workspace }}/Pipelines/Scripts/validatecode.ps1 -Directory '${{ github.workspace }}' -ChangesFile '${{ runner.temp }}/build/changed_files.txt'
      shell: pwsh

    - name: Global code validation
      if: github.event_name == 'push'
      run: |
        ${{ github.workspace }}/Pipelines/Scripts/validatecode.ps1 -Directory '${{ github.workspace }}'
      shell: pwsh